### ISSUE TITLE
ModuleNotFoundError: No module named 'G_D_model'

### ISSUE THREAD

**Issue by ghost** [zheng992328/Physics-informed-semantic-inpainting#1]
M

**Comment by zhengq01** [comment]
you can comment this line, since this file gives the definition of generator and discriminator (lines 124 and lines 153)

**Comment by PurpleHaze0404** [comment]
Hi,
I am trying to download the dataset, and requested several time to grant access to google drive, but till date did not get an access. could you please solve this issue...
best regards,

**Comment by PurpleHaze0404** [comment]
Hello, 
hope you are fine.
I have requested for the dataset but did not get any access yet. could you please solve this.
Thank you

**Comment by zheng992328** [comment]
you can download the original data for training from https://doi.org/10.6084/m9.figshare.14658759.v2

**Comment by PurpleHaze0404** [comment]
hi !
after getting the data now the following error occurs:
OSError: Unable to open file (unable to open file: name = './datasets_with_KL/kle512_lhs10000_train.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
could please give a direction
thank you

**Comment by zhengq01** [comment]
You need to generate synthetic samples by yourself according to Karhunen-Loève expansion algorithm. It is very easy and very similar to PCA. Here is a matlab code you can take as a reference.
clear all;clc
% Size of domain 
Lx = 1;  
Ly = 2;
% Discretization 
dx = 0.02;
dy = 0.05;
m = Ly/dy+1;   % row number
n = Lx/dx+1;   % column number
% Correlation lengths
lambdax = 0.1;
lambday = 0.2;
% Field mean and variance
MeanY = 2;
VarY = 1;
% Correlation function
C = nan(m*n,m*n);
x = nan(m*n,2);
for i = 1:m*n
    a = rem(i,m);       % column index
    b = fix(i/m);       % row index
    x(i,1) = (a-1)*dx;  % coordinate x
    x(i,2) = b*dy;      % coordinate y 
end
for i = 1:m*n
    for j = 1:m*n
        C(i,j) = VarY*exp(-(abs((x(i,1)-x(j,1))/lambdax)+abs((x(i,2)-x(j,2))/lambday)));
%         C(i,j) = VarY*exp(-((x(i,1)-x(j,1).^2)/(2*lambdax^2)+(x(i,2)-x(j,2).^2)/(2*lambday^2)));
    end
end
% Calculate eigenvalues and eigenvectors
kl_num = 100;          % number of KL terms that are preserved
[A1,B1] = eigs(C,kl_num);
kl_term = randn(kl_num,1);
Y = MeanY + A1*sqrt(B1)*kl_term;
figure
contourf(0:dx:Lx,0:dy:Ly,reshape(real(Y),m,n),20,'linestyle','none')
xlabel('x');
ylabel('y')
